
dist: xenial

language: python

addons:
  apt:
    packages:
    - python-matplotlib

python:
  - "2.7"
  - "3.7"
  - "3.8"
  - "3.9"

install:
    #  This requires numpy etc...
    #- pip install git+https://github.com/NeuralEnsemble/pyelectro.git

    - pip install --upgrade pip
    - pip install flake8 pytest
    - pip install .

script:
    - pynml -h
    - ./test.sh
    - ls -alt
    - flake8 . || exit 0
