name: Continuous builds

on:
  push:
    branches:
      - master
      - development
      - experimental
      - 'test*'
  pull_request:
    branches:
      - master
      - development
      - experimental
      - 'test*'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
      fail-fast: false

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version:  ${{ matrix.python-version }}

    - name: Print refs
      run: |
        echo "github.ref is: ${{ github.ref }}"
        echo "github.base_ref is: ${{ github.base_ref }}"

    - name: Install deps from development
      if: ${{ github.ref == 'refs/heads/development' || github.base_ref == 'development' }}
      run: |
        echo "Using deps from development for our repos"
        cp -v requirements-development.txt requirements.txt

    - name: Install deps from experimental
      if: ${{ github.ref == 'refs/heads/experimental' || github.base_ref == 'experimental' }}
      run: |
        echo "Using deps from experimental - assuming development in others"
        cp -v requirements-experimental.txt requirements.txt

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install .

    - name: List packages so far
      run: |
        pip list

    - name: Run tests
      run: |
        pytest --cov=pyneuroml -m "not localonly" .
        pynml -h

        ./test-ghactions.sh -neuron

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 . --count --exit-zero --show-source --max-line-length=127 --statistics
